<a href="https://colab.research.google.com/github/imanuni/imanuni/blob/main/nettoyagefile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade camel-tools[all]

Requirement already satisfied: camel-tools[all] in /usr/local/lib/python3.11/dist-packages (1.5.6)
WARNING: camel-tools 1.5.6 does not provide the extra 'all'
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (1.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (1.17.0)
Requirement already satisfied: docopt in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.6.2)
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (5.5.2)
Collecting numpy<2 (from camel-tools[all])
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (1.16.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (1.6.1)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.3.8)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (2.6.0+cu124)
Requirement already satisfied: transformers<4.44.0,>=4.0 in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (4.43.4)
Requirement already satisfied: editdistance in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.8.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (2.32.3)
Requirement already satisfied: emoji in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (2.14.1)
Requirement already satisfied: pyrsistent in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.20.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.9.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (4.67.1)
Requirement already satisfied: muddler in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (0.1.3)
Requirement already satisfied: camel-kenlm>=2025.4.8 in /usr/local/lib/python3.11/dist-packages (from camel-tools[all]) (2025.4.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (4.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools[all]) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0->camel-tools[all]) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (0.33.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (0.5.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools[all]) (0.19.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[all]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[all]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools[all]) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[all]) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[all]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[all]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools[all]) (2025.7.14)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools[all]) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools[all]) (3.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers<4.44.0,>=4.0->camel-tools[all]) (1.1.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0->camel-tools[all]) (3.0.2)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.2
    Uninstalling numpy-2.3.2:
      Successfully uninstalled numpy-2.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [2]:
!pip install --upgrade "numpy>=2.0.0,<2.3.0"

Requirement already satisfied: numpy<2.3.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (2.2.6)

In [6]:
!pip install --upgrade pandas # قمت بهذه الخطوة لأني واجهت مشاكل مع طلب (restart session) (numpy)ومع التجديد الحاصل في مكتبة

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 52.6 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
camel-tools 1.5.6 requires numpy<2, but you have numpy 2.2.6 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
Successfully installed pandas-2.3.1

In [1]:
import pandas as pd
import re

from camel_tools.utils.dediac import dediac_ar

# Nettoyage manuel

def clean_custom(text):
    # Supprimer les diacritiques (facultatif)
    text = re.sub(r'[\u064B-\u0652]', '', text)

    # Supprimer tous les chiffres (occidentaux et arabes)
    text = re.sub(r'[\d\u0660-\u0669]+', '', text)
     # Supprimer ponctuation arabe manuellement
    text = re.sub(r'[؟،؛]', '', text)  # <- ici on enlève ؟ et ses amis

    # Supprimer les ponctuations et symboles (mais garder les espaces et les deux points)
    text = re.sub(r'[^\u0600-\u06FF\s:]', '', text)

    # Réduire les espaces multiples à un seul
    text = re.sub(r'\s+', ' ', text)

    # Supprimer les espaces en début et fin
    return text.strip()


# 🔽 Télécharger et lire le fichier
from google.colab import files
uploaded = files.upload()

# Lire le fichier CSV
df = pd.read_csv('عناوين نهائي.csv', encoding='utf-8-sig')

# Nettoyage de la colonne "النص"
df['clean_text'] = df['النص'].astype(str).apply(clean_custom)

# Sauvegarde dans un fichier temporaire
df.to_csv('nettoyer.csv', index=False, encoding='utf-8-sig')

# 📤 Télécharger le fichier nettoyé
files.download('nettoyer.csv')

df.head()

Saving عناوين نهائي.csv to عناوين نهائي (3).csv

,النص,yes / no,clean_text
0,– عون: لحكومة تمثل الجميع… مطالب كتل تؤخّر الت...,yes,عون: لحكومة تمثل الجميع مطالب كتل تؤخر التأليف
1,– زيارة إيرانية للراعي: رسالة وتطمينات وسجادة ...,no,زيارة إيرانية للراعي: رسالة وتطمينات وسجادة بق...
2,– تفاؤل بحلّ قضية الودائع: على أي أسس؟!,no,تفاؤل بحل قضية الودائع: على أي أسس
3,– بوادر حملة عسكرية إسرائيلية – غربية: صنعاء ت...,no,بوادر حملة عسكرية إسرائيلية غربية: صنعاء تتحضر...
4,– وزير الخارجية السعودي إلى بيروت بين «الخميسي...,no,وزير الخارجية السعودي إلى بيروت بين الخميسين و...

الكود الموجود في الاسفل نجح في دمج : مع الاسم الذي يسبقها

In [2]:
import pandas as pd
import re
from google.colab import files

# 🔽 Upload fichier
uploaded = files.upload()

# 🔽 Lire fichier CSV
df = pd.read_csv('nettoyer.csv', encoding='utf-8-sig')
phrases = df['النص'].astype(str).tolist()

# 🔽 Fonction de normalisation arabe
def normalize_arabic(text):
    text = re.sub(r'[^\u0600-\u06FF\s:؛]', '', text)  # garder lettres arabes + : + ؛
    text = re.sub(r'[\u064B-\u0652]', '', text)
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ؤ', 'و', text)
    text = re.sub(r'ئ', 'ي', text)
    text = re.sub(r'ة', 'ه', text)
    return text

# 🔽 Coller ":"  au mot précédent (supprime espace avant)
def attach_punct_to_previous_word(text):
    return re.sub(r'\s([:])', r'\1', text)

# 🔽 Tokenisation simple par split sur espace
def simple_tokenize(text):
    return text.split()

# 🔽 Traitement complet
tokens_column = []
for phrase in phrases:
    cleaned = normalize_arabic(phrase)
    cleaned = attach_punct_to_previous_word(cleaned)
    tokens = simple_tokenize(cleaned)
    tokens_column.append(tokens)

# 🔽 Ajouter les tokens dans une nouvelle colonne
df['tokens'] = tokens_column

# 🔽 Sauvegarde et téléchargement
df.to_csv('nettoye_tokens.csv', index=False, encoding='utf-8-sig')
files.download('nettoye_tokens.csv')

df.head()

Saving nettoyer.csv to nettoyer (1).csv

,النص,yes / no,clean_text,tokens
0,– عون: لحكومة تمثل الجميع… مطالب كتل تؤخّر الت...,yes,عون: لحكومة تمثل الجميع مطالب كتل تؤخر التأليف,"[عون:, لحكومه, تمثل, الجميع, مطالب, كتل, توخر,..."
1,– زيارة إيرانية للراعي: رسالة وتطمينات وسجادة ...,no,زيارة إيرانية للراعي: رسالة وتطمينات وسجادة بق...,"[زياره, ايرانيه, للراعي:, رساله, وتطمينات, وسج..."
2,– تفاؤل بحلّ قضية الودائع: على أي أسس؟!,no,تفاؤل بحل قضية الودائع: على أي أسس,"[تفاول, بحل, قضيه, الودايع:, علي, اي, اسس؟]"
3,– بوادر حملة عسكرية إسرائيلية – غربية: صنعاء ت...,no,بوادر حملة عسكرية إسرائيلية غربية: صنعاء تتحضر...,"[بوادر, حمله, عسكريه, اسراييليه, غربيه:, صنعاء..."
4,– وزير الخارجية السعودي إلى بيروت بين «الخميسي...,no,وزير الخارجية السعودي إلى بيروت بين الخميسين و...,"[وزير, الخارجيه, السعودي, الي, بيروت, بين, الخ..."

In [3]:
import pandas as pd
import re
from google.colab import files

# 🔽 Upload fichier
uploaded = files.upload()

# 🔽 Lire fichier CSV
df = pd.read_csv('nettoye_tokens.csv', encoding='utf-8-sig')
phrases = df['clean_text'].astype(str).tolist()

# Liste personnalisée de stopwords (attention aux espaces et virgules)
custom_stopwords = ['من', 'اى', 'عن', 'الى', 'يوما', 'الآن','مما','حول','ما','نحو','كى','انا','ضدها', 'حتى', 'ثم', 'على','مهلة', 'الي', 'لا', 'ولا','في', 'لم', 'لن', 'لو', 'لدينا', 'التي', 'بين','وهي','اكثر','مع','هم','لنا','هذا','بعد','بالنسبه','لانها','ايضا','خلال','بعد','هذه','اجل','بكل','ان','ما', 'اولا',
                    'ال', 'او','كان','عليه','غير','وبعض','تحت','رغم','وطاه','كل','متى','جدا','فى', 'تحت','ونحن','ولن','وطاه','معا','والا' ,'كل','خلف', 'غير', 'عبر' ,'الـ' ,'له','عنه']

custom_stopwords = [normalize_arabic(word) for word in custom_stopwords]#ajouter ce ligne pour lire bien les stop words.

# Tokenisation simple par split sur espace
def simple_tokenize(text):
    return text.split()

# Filtrer les stopwords dans la liste des tokens
def remove_stopwords(tokens):
    return [token for token in tokens if token not in custom_stopwords]


# Traitement complet
tokens_column = []
tokens_filtered_column = []

for phrase in phrases:
    cleaned = normalize_arabic(phrase)
    cleaned = attach_punct_to_previous_word(cleaned)
    tokens = simple_tokenize(cleaned)
    tokens_column.append(tokens)
    filtered_tokens = remove_stopwords(tokens)
    tokens_filtered_column.append(filtered_tokens)

# Ajouter les tokens et les tokens filtrés dans deux colonnes
df['tokens'] = tokens_column
df['tokens_filtered'] = tokens_filtered_column

# Sauvegarder et télécharger
df.to_csv('nettoye_tokens_filtered.csv', index=False, encoding='utf-8-sig')
files.download('nettoye_tokens_filtered.csv')
df.head()

Saving nettoye_tokens.csv to nettoye_tokens (1).csv

,النص,yes / no,clean_text,tokens,tokens_filtered
0,– عون: لحكومة تمثل الجميع… مطالب كتل تؤخّر الت...,yes,عون: لحكومة تمثل الجميع مطالب كتل تؤخر التأليف,"[عون:, لحكومه, تمثل, الجميع, مطالب, كتل, توخر,...","[عون:, لحكومه, تمثل, الجميع, مطالب, كتل, توخر,..."
1,– زيارة إيرانية للراعي: رسالة وتطمينات وسجادة ...,no,زيارة إيرانية للراعي: رسالة وتطمينات وسجادة بق...,"[زياره, ايرانيه, للراعي:, رساله, وتطمينات, وسج...","[زياره, ايرانيه, للراعي:, رساله, وتطمينات, وسج..."
2,– تفاؤل بحلّ قضية الودائع: على أي أسس؟!,no,تفاؤل بحل قضية الودائع: على أي أسس,"[تفاول, بحل, قضيه, الودايع:, علي, اي, اسس]","[تفاول, بحل, قضيه, الودايع:, اسس]"
3,– بوادر حملة عسكرية إسرائيلية – غربية: صنعاء ت...,no,بوادر حملة عسكرية إسرائيلية غربية: صنعاء تتحضر...,"[بوادر, حمله, عسكريه, اسراييليه, غربيه:, صنعاء...","[بوادر, حمله, عسكريه, اسراييليه, غربيه:, صنعاء..."
4,– وزير الخارجية السعودي إلى بيروت بين «الخميسي...,no,وزير الخارجية السعودي إلى بيروت بين الخميسين و...,"[وزير, الخارجيه, السعودي, الي, بيروت, بين, الخ...","[وزير, الخارجيه, السعودي, بيروت, الخميسين, وتش..."

يوجد مشكلة في هذه المكتبة:  MorphologyDB.builtin
حيث لا يتم قراءتها ونسعها الى حلها
لذلك قمنا بالخطوة التالية بإنزال عدة TOOLS CAMEL
كما قمنا بالخطوة التي بعدها :
!camel_data -l
Cela affichera la liste des packages installés (ex. morphology-db-msa-r13, calima-msa-r13, etc.) pour confirmer que la base est présente
GitHub
.

In [36]:
!pip uninstall -y camel-tools
!pip install camel-tools
!camel_data -i light

Found existing installation: camel_tools 1.5.6
Uninstalling camel_tools-1.5.6:
  Successfully uninstalled camel_tools-1.5.6
Collecting camel-tools
  Using cached camel_tools-1.5.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from camel-tools) (1.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from camel-tools) (1.17.0)
Requirement already satisfied: docopt in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.6.2)
Requirement already satisfied: cachetools in /usr/local/lib/python3.11/dist-packages (from camel-tools) (5.5.2)
Requirement already satisfied: numpy<2 in /usr/local/lib/python3.11/dist-packages (from camel-tools) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from camel-tools) (1.16.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from camel-tools) (2.3.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from camel-tools) (1.6.1)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.3.8)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.11/dist-packages (from camel-tools) (2.6.0+cu124)
Requirement already satisfied: transformers<4.44.0,>=4.0 in /usr/local/lib/python3.11/dist-packages (from camel-tools) (4.43.4)
Requirement already satisfied: editdistance in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.8.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from camel-tools) (2.32.3)
Requirement already satisfied: emoji in /usr/local/lib/python3.11/dist-packages (from camel-tools) (2.14.1)
Requirement already satisfied: pyrsistent in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.20.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.9.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from camel-tools) (4.67.1)
Requirement already satisfied: muddler in /usr/local/lib/python3.11/dist-packages (from camel-tools) (0.1.3)
Requirement already satisfied: camel-kenlm>=2025.4.8 in /usr/local/lib/python3.11/dist-packages (from camel-tools) (2025.4.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (4.14.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0->camel-tools) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0->camel-tools) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (0.33.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (2024.11.6)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (0.5.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.11/dist-packages (from transformers<4.44.0,>=4.0->camel-tools) (0.19.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->camel-tools) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->camel-tools) (2025.7.14)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->camel-tools) (3.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers<4.44.0,>=4.0->camel-tools) (1.1.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0->camel-tools) (3.0.2)
Using cached camel_tools-1.5.6-py3-none-any.whl (124 kB)
Installing collected packages: camel-tools
Successfully installed camel-tools-1.5.6
No new packages will be installed.

In [37]:
!camel_data -l

Package Name                      Size  License     Description
----------------------------  --------  ----------  -------------------------------------------------------------------------------------------------------------------------
all                                                 All available CAMeL Tools packages
defaults                                            Default datasets for all CAMeL Tools components
dialectid-all                                       All available dialect identification models
dialectid-model26             371.2 MB  MIT         Dialect identification model trained to differentiating between 25 Arabic city dialects as well as Modern Standard Arabic
dialectid-model6              153.0 MB  MIT         Dialect identification model trained to differentiating between 5 Arabic city dialects as well as Modern Standard Arabic
disambig-bert-unfactored-all                        All available unfactored BERT disambiguation models
disambig-bert-unfactored-egy  445.5 MB  MIT         Unfactored BERT model for disambiguating Egyptian Arabic
disambig-bert-unfactored-glf  442.3 MB  MIT         Unfactored BERT model for disambiguating Gulf Arabic
disambig-bert-unfactored-lev  441.2 MB  MIT         Unfactored BERT model for disambiguating Levantine Arabic
disambig-bert-unfactored-msa  445.0 MB  MIT         Unfactored BERT model for disambiguating Modern Standard Arabic
disambig-mle-all                                    All available MLE disambiguation models
disambig-mle-calima-egy-r13    27.2 MB  GPL v2      MLE model for disambiguating Egyptian Arabic
disambig-mle-calima-msa-r13    88.7 MB  GPL v2      MLE model for disambiguating Modern Standard Arabic
light                                               A minimal set of packages for performing morphological analysis, disambiguation, and dialect identification.
morphology-db-all                                   All available morphology databases
morphology-db-egy-r13          67.3 MB  GPL v2      Database for analyzing Egyptian Arabic
morphology-db-glf-01            8.0 MB  CC BY 4.0   Database for analyzing Gulf Arabic
morphology-db-lev-01           10.6 MB  CC BY 4.0   Database for analyzing Levantine Arabic
morphology-db-msa-r13          40.5 MB  GPL v2      Database for analyzing Modern Standard Arabic
morphology-db-msa-s31          44.8 MB  LDC         Database for analyzing Modern Standard Arabic
ner-all                                             All available named-entity-recognition models
ner-arabert                   541.6 MB  AraBERT     Named Entity Recognition model generated by fine-tuning AraBERT
sentiment-analysis-all                              All available sentiment analysis models
sentiment-analysis-arabert    541.6 MB  AraBERT     Sentiment Analysis model generated by fine-tuning AraBERT
sentiment-analysis-mbert      712.5 MB  Apache 2.0  Sentiment Analysis model generated by fine-tuning Multilingual BERT

In [38]:
from camel_tools.morphology.database import MorphologyDB
from camel_tools.morphology.analyzer import Analyzer

db = MorphologyDB.builtin_db()
analyzer = Analyzer(db)

In [41]:
from camel_tools.utils.dediac import dediac_ar
import ast
# Charger ton fichier (si nécessaire)
from google.colab import files
uploaded = files.upload()  # Choisis le fichier stam-lam.csv
df = pd.read_csv('stam-lam.csv', encoding='utf-8-sig')

# Parser la colonne 'tokens_filtered' (listes stockées sous forme de chaînes)
df['tokens_filtered'] = df['tokens_filtered'].apply(ast.literal_eval)

lemmes_col = []
racines_col = []

for tokens in df['tokens_filtered']:
    lemmas = []
    roots = []
    for token in tokens:
        analyses = analyzer.analyze(token)
        if analyses:
            lemmas.append(analyses[0]['lex'])   # LAM
            roots.append(analyses[0]['root'])   # STAM
        else:
            lemmas.append(token)
            roots.append(token)
    lemmes_col.append(lemmas)
    racines_col.append(roots)

# Ajouter au DataFrame
df['lemmes'] = lemmes_col
df['racines'] = racines_col

# Sauvegarder le nouveau CSV
df.to_csv('corpus_lemmatise_racinise.csv', index=False, encoding='utf-8-sig')

# Télécharger
from google.colab import files
files.download('corpus_lemmatise_racinise.csv')

# Afficher un aperçu
df[['tokens_filtered', 'lemmes', 'racines']].head()

Saving stam-lam.csv to stam-lam (1).csv

,tokens_filtered,lemmes,racines
0,"[عون:, لحكومه, تمثل, الجميع, مطالب, كتل, توخر,...","[عون:, حُكُومَة, تَمَثُّل, جَمِيع, مُطالَب, كُ...","[عون:, ح.ك.م, م.ث.ل, ج.م.ع, ط.ل.ب, ك.ت.ل, توخر..."
1,"[زياره, ايرانيه, للراعي:, رساله, وتطمينات, وسج...","[زِيارَة, إِيرانِيّ, للراعي:, رِسالَة, تَطْمِي...","[ز.#.ر, NTWS, للراعي:, ر.س.ل, ط.م.ن, س.ج.د, ق...."
2,"[تفاول, بحل, قضيه, الودايع:, اسس]","[تفاول, حِلّ, قَضِيَّة, الودايع:, أَساس]","[تفاول, ح.ل.ل, ق.ض.#, الودايع:, #.س.س]"
3,"[بوادر, حمله, عسكريه, اسراييليه, غربيه:, صنعاء...","[بادِرَة, حَمْل, عَسْكَرِيّ, اسراييليه, غربيه:...","[ب.د.ر, ح.م.ل, ع.س.ك.ر, اسراييليه, غربيه:, ص.ن..."
4,"[وزير, الخارجيه, السعودي, بيروت, الخميسين, وتش...","[وَزِير, خارِجِيّ, سَعُودِيّ, بَيْرُوت, الخميس...","[#.ز.ر, خ.ر.ج, س.ع.د, ب.#.ر.ت, الخميسين, وتشاو..."